description: |
  The buttons chosen for this website have a focus on the minimalist and round style that is incorporated throughout the branding.

  Buttons can be combined with cards, banners, and forms.

patterns:
  light-btn:
    title: "Light Button"
    description: |
      The <i>Light Button</i> is to be used throughout the website as the default button style. It can be placed on cards & banners with a dark background.
    fields:
      - name: text
        type: string
        example: "Case Studies"
      - name: url
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Link to case studies page"
  dark-btn:
    title: "Dark Button"
    description: |
      The <i>Dark Button</i> is to be used throughout the website as the default button style. It can be placed on cards & banners with a light background.
    fields:
      - name: text
        type: string
        example: "Submit"
      - name: url
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Link to case studies page"
  form-btn:
    title: "Form Button"
    description: |
      The <i>Form Button</i> is to be used on the form as it includes the type to create a workable form.
  card-btn:
    title: "Card Button"
    description: |
      The <i>Card Button</i> is to be used on any cards that link to a project page.
    fields:
      - name: text
        type: string
        example: "Check it out!"
      - name: url
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Link to case studies page"
  cta-btn:
    title: "CTA Button"
    description: |
      The <i>CTA Button</i> is to be used on any call-to-action banners that navigate throughout the portfolio website.
    fields:
      - name: text
        type: string
        example: "Check it out!"
      - name: url
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Link to case studies page"
