description: |
  The sections are to be used throughout the website in areas with large amounts of content where there are multiple elements present.

  Sections are combined with text, images, buttons, cards, and navigation.

patterns:
  pillars:
    title: "Pillars Section"
    description: |
      The <i>Pillars Section</i> is to be used on the projects page to showcase the three goals of the project. This can be combined with icons and text.
    fields:
      - name: section_bgcolor
        type: string
        example: "background-color-athenaxnova"
      - name: image1
        type: string
        example: "customers"
      - name: image2
        type: string
        example: "computer"
      - name: image3
        type: string
        example: "brand-identity"
      - name: header1
        type: string
        example: "Goal 1"
      - name: header2
        type: string
        example: "Goal 2"
      - name: header3
        type: string
        example: "Goal 3"
  default-text:
    title: "Default Text Section"
    description: |
      The <i>Default Text Section</i> is to be used anywhere on the website where there is a chunk of text that needs to be placed with styling.
    fields:
      - name: text1
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: text2
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: text3
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: code
        type: string
        example: "<h1>"
      - name: closing-code
        type: string
        example: "</h1>"
      - name: header
        type: string
        example: "Who am I?"
  header-text:
    title: "Header Text Style"
    description: |
      The <i>Header Text Style</i> is to be used anywhere where there is a header on the website.
    fields:
      - name: header
        type: string
        example: "Who am I?"
      - name: code
        type: string
        example: "<h1>"
      - name: closing-code
        type: string
        example: "</h1>"
  project-info:
    title: "Project Info Section"
    description: |
      The <i>Project Info Section</i> is to be presented on every project page to showcase the imagery and description of the project itself. It can be combined with text and navigation.
    fields:
      - name: section_text
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: section_code
        type: string
        example: "<h1>"
      - name: section_closing-code
        type: string
        example: "</h1>"
      - name: section_color
        type: string
        example: "code-text"
      - name: section_header
        type: string
        example: "Who am I?"
  tabbed-interface:
    title: "Tabbed Interface Section"
    description: |
      The <i>Tri Project Info Section</i> will be used on the projects page in order to showcase details and imagery on the subject of the projects purpose & goal, target audience, & concepts. This can be combined with navigation and images.
    fields:
      - name: image1
        type: string
        example: "placeholder-1by1.jpg"
      - name: image2
        type: string
        example: "placeholder-1by1.jpg"
      - name: image3
        type: string
        example: "placeholder-1by1.jpg"
      - name: purpose
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: goal
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: audience
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: concepts
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: sitemap-text
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: sitemap
        type: string
        example: "placeholder-3by2.jpg"
      - name: branding
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: moodboard
        type: string
        example: "placeholder-3by2.jpg"
      - name: prototype
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: navigation_image1
        type: string
        example: "placeholder-3by2.jpg"
      - name: navigation_image5
        type: string
        example: "placeholder-3by2.jpg"
      - name: navigation_image6
        type: string
        example: "placeholder-3by2.jpg"
      - name: navigation_image7
        type: string
        example: "placeholder-3by2.jpg"
      - name: development1
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: development2
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: development3
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: development4
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      - name: list1
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list2
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list3
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list4
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list5
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list6
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list7
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list8
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list9
        type: string
        example: "•	setting up hosting through Netlify"
      - name: list10
        type: string
        example: "•	setting up hosting through Netlify"
      - name: hidden
        type: string
        example: "null"
  project-cards:
    title: "Project Cards"
    description: |
      The <i>Project Cards</i> will be used as a call-to-action for the projects.
  video:
    title: "Video"
    description: |
      The <i>Video</i> can be used for any pages that contain videos.
    fields:
      - name: video
        type: string
        example: "bearcreeksanctuary-parallax.mp4"
  seo:
    title: "SEO"
    description: |
      The <i>SEO</i> will be used on every layout page as it contains the general data for search engine optimization.
