description: |
  The sections are to be used throughout the website in areas with large amounts of content where there are multiple elements present.

  Sections are combined with text, images, buttons, cards, and navigation.

patterns:
  pillars:
    title: "Pillars Section"
    description: |
      The <i>Pillars Section</i> is to be used on the projects page to showcase the three goals of the project. This can be combined with icons and text.
    fields:
      - name: section_bgcolor
        type: string
        example: "background-color-athenaxnova"
      - name: cards_image1
        type: string
        example: "circle-placeholder.png"
      - name: cards_image2
        type: string
        example: "circle-placeholder.png"
      - name: cards_image3
        type: string
        example: "circle-placeholder.png"
      - name: cards_header1
        type: string
        example: "Goal 1"
      - name: cards_header2
        type: string
        example: "Goal 2"
      - name: cards_header3
        type: string
        example: "Goal 3"
  default-text:
    title: "Default Text Section"
    description: |
      The <i>Default Text Section</i> is to be used anywhere on the website where there is a chunk of text that needs to be placed with styling.
    fields:
      - name: text
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: code
        type: string
        example: "<h1>"
      - name: closing-code
        type: string
        example: "</h1>"
      - name: color
        type: string
        example: "code-text"
      - name: header
        type: string
        example: "Who am I?"
  header-text:
    title: "Header Text Style"
    description: |
      The <i>Header Text Style</i> is to be used anywhere where there is a header on the website.
    fields:
      - name: header
        type: string
        example: "Who am I?"
      - name: code
        type: string
        example: "<h1>"
      - name: closing-code
        type: string
        example: "</h1>"
  project-info:
    title: "Project Info Section"
    description: |
      The <i>Project Info Section</i> is to be presented on every project page to showcase the imagery and description of the project itself. It can be combined with text and navigation.
    fields:
      - name: section_text
        type: string
        example: "I believe that the time we spend on this beautiful planet should be of value. I believe that we should protect this planet and all that surrounds us. I believe that we all have the ability to make a difference and that any small change has a ripple effect for the greater good."
      - name: section_code
        type: string
        example: "<h1>"
      - name: section_closing-code
        type: string
        example: "</h1>"
      - name: section_color
        type: string
        example: "code-text"
      - name: section_header
        type: string
        example: "Who am I?"
      - name: navigation_image1
        type: string
        example: "placeholder-1.jpg"
      - name: navigation_image2
        type: string
        example: "placeholder-2.jpg"
      - name: navigation_image3
        type: string
        example: "placeholder-3.jpg"
      - name: navigation_image4
        type: string
        example: "placeholder-4.jpg"
  tri-project-info:
    title: "Tri Project Info Section"
    description: |
      The <i>Tri Project Info Section</i> will be used on the projects page in order to showcase details and imagery on the subject of the projects purpose & goal, target audience, & concepts. This can be combined with navigation and images.
  quart-project-info:
    title: "Quart Project Info Section"
    description: |
      The <i>Quart Project Info Section</i> will be used on the projects page in order to showcase details and imagery on the subject of the projects research, branding, design, & development process. This can be combined with navigation and images.
