description: |
  The card section is to be used where there is need to a section that includes multiple pieces that join into a card style.

  Cards can be combined with icons, buttons, and sections.

patterns:
  pillar:
    title: "Pillar Card"
    description: |
      The <i>Pillar Card</i> can be used in the pillars section where there will be multiple cards placed beside one another.
    fields:
      - name: image
        type: string
        example: "circle-placeholder.png"
      - name: header
        type: string
        example: "Placeholder"
