description: |
  The navigation section is where one can find all the forms of navigation that can be present on this website.

  Navigation can be combined with sections.

patterns:
  carousel:
    title: "Image Carousel"
    description: |
      The <i>Image Carousel</i> can be used in place of where there needs to be multiple images shown in the form of a slideshow.
    fields:
      - name: image1
        type: string
        example: "placeholder-1.jpg"
      - name: image2
        type: string
        example: "placeholder-2.jpg"
      - name: image3
        type: string
        example: "placeholder-3.jpg"
      - name: image4
        type: string
        example: "placeholder-4.jpg"
  tabbed-carousel:
    title: "Tabbed Image Carousel"
    description: |
      The <i>Tabbed Image Carousel</i> can be used in place of where there needs to be multiple images shown in the form of a slideshow under the tabbed interface section.
    fields:
      - name: image5
        type: string
        example: "placeholder-1.jpg"
      - name: image6
        type: string
        example: "placeholder-2.jpg"
      - name: image7
        type: string
        example: "placeholder-3.jpg"
